---

- name: Install thanos from repo
  apt:
    name: "thanos{{ '' if thanos_package_version == 'latest' else '=' + thanos_package_version }}"
    state: "{{ 'latest' if thanos_package_version == 'latest' else 'present' }}"
    cache_valid_time: 3600
  notify: restart thanos

- name: Mark Thanos package to HOLD
  command: "apt-mark hold thanos"

# Configure the query backend, systemd files, etc
- name: validate that required variables are set
  assert:
    that:
      - '{{ item }} != ""'
    msg: "{{ item }} must be set"
  with_items:
    - thanos_s3_bucket_name
    - thanos_s3_endpoint
    - thanos_prometheus_url
    - thanos_prometheus_data_dir

- name: create prometheus system group
  group:
    name: prometheus
    system: true
    state: present
