---
- name: "Sidecar: Install thanos sidecar systemd file"
  template:
    src: thanos-sidecar.j2
    dest: /etc/systemd/system/thanos-sidecar.service
  register: sidecar_systemd
  notify: restart thanos-sidecar

- name: "Sidecar: Reload systemd if thanos sidecar changed"
  systemd:
    daemon_reload: true

- name: "Sidecar: Add defaults file"
  template:
    src: thanos-sidecar-defaults.j2
    dest: /etc/default/thanos-sidecar
  notify: restart thanos-sidecar

- name: "Sidecar: generate configuration file"
  template:
    group: prometheus
    src: thanos-s3-config.j2
    dest: "{{ thanos_sidecar_config_file }}"
  notify: restart thanos-sidecar
  
- name: "Sidecar: generate tracing configuration file"
  copy:
    group: prometheus
    content: "{{ thanos_sidecar_tracing_config }}"
    dest: "{{ thanos_sidecar_tracing_config_file }}"
  when: thanos_sidecar_tracing_config_file is defined
  notify: restart thanos-sidecar

- name: "Sidecar: Ensure thanos-sidecar is started"
  service:
    name: thanos-sidecar
    enabled: true
    state: started

- name: "Check if node exporter directory exists"
  stat:
    path: /etc/prometheus-node-exporter
  register: node_exporter

- name: "Add node exporter files"
  when: node_exporter.stat.exists is defined and node_exporter.stat.exists
  block:
    - set_fact: service_name="thanos-sidecar"

    - name: "Add the node exporter file to path"
      template:
        src: node-exporter.sh.j2
        dest: /usr/local/bin/prometheus-service-restart.sh
        owner: root
        group: root
        mode: 0775

    - name: "Set up cronjob for node exporter"
      cron:
        name: "Run systemd restart count"
        minute: "*/1"
        job: "/usr/local/bin/prometheus-service-restart.sh"
